#!/usr/bin/env bash
set -euo pipefail

CONFIG="${1:-configs/power/nvml_policy.yaml}"
MODE="${2:---all}"
ITER_ID="${ITER_ID:-iter_001}"
LOG_DIR="experiments/logs"
mkdir -p "${LOG_DIR}" experiments/raw/microbench_power experiments/processed/microbench experiments/reports "experiments/dynamic_power/${ITER_ID}"
LOG_FILE="${LOG_DIR}/03_run_microbenchmarks_$(date +%Y%m%d_%H%M%S).log"

{
  echo "stage=03_run_microbenchmarks"
  echo "iter_id=${ITER_ID}"
  echo "config=${CONFIG}"
  echo "mode=${MODE}"
  echo "command=$0 $*"
  echo "TODO: implement modes --build-only, --power-only, --profile-only, --all"
  echo "TODO: build microbenchmark binaries for Phase 07"
  echo "TODO: run energy mode with src/power/nvml_sampler.py for Phase 08"
  echo "example_energy_command:"
  echo "  GPU_ID=0 python src/power/nvml_sampler.py --config ${CONFIG} --gpu-id 0 --output-dir experiments/raw/microbench_power/<bench_id> --label microbench_<bench_id> -- ./<microbench_binary> <args>"
  echo "TODO: run profiler mode with NCU for Phase 09"
  echo "TODO: dump SASS for each binary for Phase 07/09"
  echo "TODO: reject or quarantine benchmarks with negative measured or baseline-subtracted dynamic power"
  echo "expected_outputs:"
  echo "  experiments/processed/microbench/build_manifest.yaml"
  echo "  experiments/processed/microbench/sass_verification/<bench_id>.sass"
  echo "  experiments/raw/microbench_power/<bench_id>/power_trace.csv"
  echo "  experiments/processed/microbench/sass_counts.*"
  echo "  experiments/processed/microbench/cache_metrics.*"
  echo "  experiments/processed/microbench/microbench_matrix_inputs.*"
  echo "  experiments/reports/phase07_microbench_build.md"
  echo "  experiments/reports/phase08_microbench_power.md"
  echo "  experiments/reports/phase09_sass_count_and_ncu_extract.md"
} | tee "${LOG_FILE}"
